[package]
name = "ray-tracing-in-one-weekend-rs"
version = "0.1.0"
authors = ["Danny Fritz <dannyfritz@gmail.com>"]

[dependencies]
image = "0.19.0"
rand = "0.5.3"
ncollide3d = "0.16.2"
nalgebra = "0.15.3"
flame = { version = "0.2.2", optional = true }

[features]
default = []
profile = ["flame"]